### ISSUE TITLE
Can't add menu item in main menu

### ISSUE THREAD

**Issue by marinat** [mozilla-jetpack/jpm-mobile#11]
I can't find information about adding menu items in main menu. Before I added it so:
function addMenuItem(window) {  
  menuID = window.NativeWindow.menu.add({  
    name: "Show Toast",  
    callback: function(){  
      showToast(window);   
    }  
  });  
}
But in jpm I have no object window. Is it possible to add menu item in jpm?

**Comment by kumar303** [comment]
jpm-mobile is just a tool to work with your mobile device during development. I think you'll get a better answer to this question either in `#extdev` on `irc.mozilla.org` or in one of the forums:

https://discourse.mozilla-community.org/c/add-ons/development
http://stackoverflow.com/questions/tagged/firefox-addon
