### ISSUE TITLE
Running jpm-mobile from the command line errors out

### ISSUE THREAD

**Issue by freaktechnik** [mozilla-jetpack/jpm-mobile#5]
```trace
/home/travis/.nvm/v0.10.36/lib/node_modules/jpm-mobile/bin/jpm-mobile:50
if (cmd.isEmptyCommand(program)) {
    ^
ReferenceError: cmd is not defined
    at Object.<anonymous> (/home/travis/.nvm/v0.10.36/lib/node_modules/jpm-mobile/bin/jpm-mobile:50:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:929:3
```
from https://travis-ci.org/freaktechnik/jetpack-homepanel

JPM seems to get the cmd object from https://github.com/mozilla/jpm/blob/master/bin/jpm#L10, which jpm-mobile doesn't have.

**Comment by ronald05arias** [comment]
+1

**Comment by Aeyoun** [comment]
Still an issue.

**Comment by jalefkowit** [comment]
I'm hitting this problem too.

**Comment by hashemian** [comment]
@ncalexan patch fixed the issue for me. I had to cherrypick it separately though.

**Comment by meitar** [comment]
Patched fixed the issue for me, too.

**Comment by erikvold** [comment]
@jsantell who has permissions besides you to review pull requests for this repo?

**Comment by chatziko** [comment]
+1
jpm-mobile is completely broken because of this.

For the impatient:

    sudo npm install -g ncalexan/jpm-mobile#fixes

**Comment by Rudloff** [comment]
Any news on this? Is jpm-mobile still updated?
