### ISSUE TITLE
Using `jpm-mobile run` fails to start Firefox on Adroid with "Activity class {/mnt/sdcard/jetpack-profile} does not exist" error

### ISSUE THREAD

**Issue by meitar** [mozilla-jetpack/jpm-mobile#9]
I encountered the following issue while trying to `jpm-mobile run` as I was developing an add-on.

```
$ jpm-mobile run --adb `which adb` -b firefox
[…SNIPPED…]
Pushed the addon to your device
Running Firefox instance ...
Starting Firefox with /mnt/sdcard/jetpack-profile
--------- beginning of main
Starting: Intent { act=android.activity.MAIN cmp=/mnt/sdcard/jetpack-profile (has extras) }
--------- beginning of system
Error type 3
Error: Activity class {/mnt/sdcard/jetpack-profile} does not exist.
```

I traced this issue to the `amStart()` method in `adb.js` that fails to properly quote an argument sent to `spawn`. The [offending line](https://github.com/mozilla-jetpack/jpm-mobile/blob/86b7f6421c017a291665335d723d1bbb38d65b96/lib/adb.js#L73):

```javascript
              "-profile " + options.profile
```

Should be:

```javascript
              "'-profile " + options.profile + "'"
```

**Comment by erikvold** [comment]
@jsantell ping

**Comment by fortuna** [comment]
Is there a workaround?

It would be great if this was prioritized. This error and #4 are blockers for add-on developers. If Mozilla seriously wants developers to build add-ons for Firefox mobile, this should be fixed as soon as possible.

I'm trying to make a Desktop add-on work for Android, and so far it's been a terrible experience. 😞

**Comment by fortuna** [comment]
Here's a workaround:

    sudo npm install varavut/jpm-mobile -g

That seems to be the most updated fork.
